# Configuracion de red - SGF
# Cambiar IPs para despliegue en red real  127.0.0.1 es el loopback cuando es en la misma maquina. 

directorio.ip=127.0.0.1
directorio.puerto=4040
monitor.ip=127.0.0.1
monitor.puerto=5050